### ISSUE TITLE
AttributeError: 'Function' object has no attribute 'set_user_xref'

### ISSUE THREAD

**Issue by xpcmdshell** [trailofbits/ObjCGraphView#3]
Sample executables to reproduce issue (MacOS 10.14.5):
```
/System/Library/PrivateFrameworks/XCTAutomationSupport.framework/Versions/A/XPCServices/LogArchiveCollector.xpc/Contents/MacOS/LogArchiveCollector

/System/Library/PrivateFrameworks/ClassroomKit.framework/Versions/A/XPCServices/BooksService.xpc/Contents/MacOS/BooksService
```

Steps to reproduce: 
1. Open one of the above executables
2. Tools -> Objc -> Run All
3. Check console output, you should see similar to the following:
```Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/plugin.py", line 647, in run
    self.task.run()
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/ObjCGraphView/__init__.py", line 62, in run
    define_methods(self.view)
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/ObjCGraphView/methods.py", line 64, in define_methods
    _add_xrefs(view)
  File "/Users/user/Library/Application Support/Binary Ninja/plugins/ObjCGraphView/methods.py", line 476, in _add_xrefs
    xref.function.set_user_xref(call_mlil.address, function.start)
AttributeError: 'Function' object has no attribute 'set_user_xref'
```

I didn't find set_user_xref in the API docs, and the same behavior is seen on dev and stable branches. Binja is using Python 3.7.3 installed through homebrew on this machine. Let me know if there's any more info you'd like about my setup to help triage this. Thanks!

**Comment by joshwatson** [comment]
Just pull again. They changed the API on me and I fixed it a couple days ago 🙂

You do need to be on dev though for sure.
